name: mqtt_chat_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.6
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  open_filex: ^4.3.2
  path_provider: ^2.0.12
  flutter_chat_types: ^3.6.0
  http: ^1.2.0
  intl: ^0.19.0
  mime: ^1.0.4
  uuid: ^4.3.3
  shared_preferences: ^2.0.17
  ffi: ^2.1.0
  flutter_rust_bridge: ^1.82.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^9.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/messages.json
    - assets/smr.png
